let level1;
function initLevel() {
  level1 = new Level(
    [
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new BabyChicken(),
      new BabyChicken(),
      new BabyChicken(),
      new BabyChicken(),
      new BabyChicken(),
      new BabyChicken(),
      new BabyChicken(),
      new BabyChicken(),
      new BabyChicken(),
      new Endboss(),
    ],
    [
      new Coin(580, 180),
      new Coin(1000, 100),
      new Coin(1480, 280),
      new Coin(1800, 200),
      new Coin(2600, 160),
      new Bottle(1458, 340),
      new Bottle(731, 299),
      new Bottle(2025, 189),
      new Bottle(1045, 340),
      new Bottle(1672, 156),
      new Bottle(493, 214),
      new Bottle(2400, 120),
      new Bottle(2700, 350),
      new Bottle(3000, 120),
      new Bottle(2200, 350)
    ],
    [
      new Cloud("img/5_background/layers/4_clouds/1.png", 0),
      new Cloud("img/5_background/layers/4_clouds/2.png", 720),
      new Cloud("img/5_background/layers/4_clouds/1.png", 1440),
      new Cloud("img/5_background/layers/4_clouds/2.png", 2160),
      new Cloud("img/5_background/layers/4_clouds/2.png", 2880),
      new Cloud("img/5_background/layers/4_clouds/2.png", 3600),
      new Cloud("img/5_background/layers/4_clouds/2.png", 4320),
    ],
    [
      new BackgroundObject("img/5_background/layers/air.png", -719),
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", -719),
      new BackgroundObject("img/5_background/layers/2_second_layer/2.png", -719),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png", -719),
      new BackgroundObject("img/5_background/layers/air.png", 0),
      new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 0),
      new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 0),
      new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 0),
      new BackgroundObject("img/5_background/layers/air.png", 719),
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 719),
      new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 719),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 719),
      new BackgroundObject("img/5_background/layers/air.png", 719 * 2),
      new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 719 * 2),
      new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 719 * 2),
      new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 719 * 2),
      new BackgroundObject("img/5_background/layers/air.png", 719 * 3),
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 719 * 3),
      new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 719 * 3),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 719 * 3),
      new BackgroundObject("img/5_background/layers/air.png", 719 * 4),
      new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 719 * 4),
      new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 719 * 4),
      new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 719 * 4),
      new BackgroundObject("img/5_background/layers/air.png", 719 * 5),
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 719 * 5),
      new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 719 * 5),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 719 * 5),
    ]
  );
}
